choongang2022/team-project

choongangGroup/src/main/java/com/oracle/choongangGroup/domain/professor/Attendance.java
choongangGroup/src/main/java/com/oracle/choongangGroup/domain/professor/Lecture.java
choongangGroup/src/main/java/com/oracle/choongangGroup/domain/professor/Lecture_MemberPK.java
choongangGroup/src/main/java/com/oracle/choongangGroup/domain/professor/Makeup.java
choongangGroup/src/main/java/com/oracle/choongangGroup/domain/professor/Report.java
choongangGroup/src/main/java/com/oracle/choongangGroup/domain/professor/Score.java
choongangGroup/src/main/java/com/oracle/choongangGroup/domain/professor/Subject.java

[동호] 교수 domain 수정

---

choongangGroup/src/main/java/com/oracle/choongangGroup/domain/manager/Approval.java
choongangGroup/src/main/java/com/oracle/choongangGroup/domain/manager/Work.java
choongangGroup/src/main/java/com/oracle/choongangGroup/domain/manager/WorkPK.java
choongangGroup/src/main/java/com/oracle/choongangGroup/domain/manager/WorkStatus.java
choongangGroup/src/main/java/com/oracle/choongangGroup/domain/professor/Lecture.java

[혜선]결재, 강의 수정

---

choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/Approval.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalDao.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalDaoImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalRestController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalService.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalServiceImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/MemDeptDao.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/MemDeptDaoImpl.java
choongangGroup/src/main/resources/mappers/Approval.xml
choongangGroup/src/main/resources/mappers/MemDept.xml
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalForm.jsp

[혜선] 결재 글쓰기 구현

---

choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/Approval.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalDao.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalDaoImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalRestController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalService.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalServiceImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/MemDeptDao.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/MemDeptDaoImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/Paging.java
choongangGroup/src/main/resources/mappers/Approval.xml
choongangGroup/src/main/resources/mappers/MemDept.xml
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalEndForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalProcessDetail.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalProcessForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalWaitForm.jsp

[혜선] 결재 완료 페이징 및 기안 진행 결재 취소 구현

[혜선] 결재 완료 페이징 및 기안 진행 결재 취소 구현

---

choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/GetMember.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/LoginSuccessHandler.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/SecurityController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/DhProfessorController.java
choongangGroup/src/main/webapp/WEB-INF/views/professor/report.jsp

[동호] 로그인 유저 member 받는 class 추가 GetMember

[동호] 로그인 유저 member 받는 class 추가 GetMember

---

choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalDaoImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalRestController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementDao.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementDaoImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementService.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementServiceImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LectureVO.java
choongangGroup/src/main/resources/configuration.xml
choongangGroup/src/main/resources/mappers/LectureVO.xml
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalEndForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalProcessForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalWaitForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/lecManagementForm.jsp

[혜선] 결재 수정 및 강의 승인 페이지 구현

---

choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/JwtAuthenticationFilter.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/SecurityController.java
choongangGroup/src/main/webapp/WEB-INF/views/professor/main.jsp

[동호] "/" 페이지 요청 시 token 확인 후 유효하면 role별 main으로 연결, else 로그인 페이지로 연결

[동호] "/" 페이지 요청 시 token 확인 후 유효하면 role별 main으로 연결, else 로그인 페이지로 연결

---

choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/JwtAuthenticationFilter.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/JwtTokenProvider.java

[동호] token 유효성 검증시 exception 처리 개선

[동호] token 유효성 검증시 exception 처리 개선

---

choongangGroup/src/main/webapp/WEB-INF/views/loginForm.jsp

[동호] 로그인 시 alert('성공') 제거

---

choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/JwtAuthenticationFilter.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/JwtTokenProvider.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/SecurityController.java
choongangGroup/src/main/resources/application.yml
choongangGroup/src/main/webapp/WEB-INF/views/professor/main.jsp
choongangGroup/src/main/webapp/WEB-INF/views/professor/report.jsp

Reverts choongang2022/team-project#96

Revert "[동호] 수정"

---

choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalRestController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/InsertLecOrdersDto.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementDao.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementDaoImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementService.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementServiceImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LectureVO.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/MakeupMapper.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/managerPage/ManagerPageController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/managerPage/ManagerPageRepository.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/managerPage/ManagerPageRepositoryImpl.java
choongangGroup/src/main/resources/mappers/LecOrders.xml
choongangGroup/src/main/resources/mappers/LectureVO.xml
choongangGroup/src/main/webapp/WEB-INF/views/manager/lecManagementForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/mypage.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/studentManage.jsp

[혜선] 강의승인 개설 수정 및 학생관리

---

choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/JwtAuthenticationFilter.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/JwtTokenProvider.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/SecurityController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/SecurityService.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/SecurityServiceImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/SecurtiyConfig.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/TokenInfo.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/LectureMapper.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/makeup/DhProfessorMakeupController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/makeup/DhProfessorMakeupSerivce.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/makeup/DhProfessorMakeupServiceImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/makeup/OrdersDto.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/mappers/OrdersMapper.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/report/DhProfessorReportController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/report/DhProfessorReportService.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/report/DhProfessorReportServiceImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/repository/DhProfessorAppLecRepository.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/repository/DhProfessorLecRepository.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/repository/DhProfessorReportRepository.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/InsertLecOrdersDto.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementServiceImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/MakeupMapper.java
choongangGroup/src/main/resources/mappers/LecOrders.xml
choongangGroup/src/main/webapp/WEB-INF/views/loginForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/professor/makeup.jsp
choongangGroup/src/main/webapp/WEB-INF/views/professor/report.jsp

[동호] 자동로그인 기능 추가, 교수 휴/보강 기능 추가(혜선파트 수정 있음)

[동호] 자동로그인 기능 추가, 교수 휴/보강 기능 추가(혜선파트 수정 있음)

---

choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/SecurityController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/SecurityServiceImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/lecturePlan/DhProLecPlanController.java
choongangGroup/src/main/webapp/WEB-INF/views/professor/lecPlan.jsp

[동호] 충돌수정 mian.jsp, 강의계획서 jps 추가

---

choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/Approval.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/approval/ApprovalController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementController.java
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalEndDetail.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalEndForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalMain.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalProcessDetail.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalProcessForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalWaitDetail.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalWaitForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/lecManagementForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/main.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/makeupManagement.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/mypage.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/professorManage.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/studentManage.jsp

[혜선] 결재, 학사, 메인 연결

---

choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/LoginSuccessHandler.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/PrincipalDetailsService.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/SecurityController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/auth/SecurityRepository.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/lecturePlan/DhLecPlanServiceImpl.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/lecturePlan/DhProLecPlanController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/lecturePlan/DhProLecPlanService.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/lecturePlan/InsertPlanDto.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/lecturePlan/LecPlanDto.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/lecturePlan/LecPlanLecDto.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/lecturePlan/LecPlanSql.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/lecturePlan/LecPlanWeekDto.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/lecturePlan/PlanWeekArray.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/lecturePlan/ShowPlanDetailDto.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/mappers/LecPlanMapper.java
choongangGroup/src/main/java/com/oracle/choongangGroup/dongho/professor/mappers/LecPlanWeekMapper.java
choongangGroup/src/main/resources/mappers/LecPlan.xml
choongangGroup/src/main/resources/mappers/lecPlanWeek.xml
choongangGroup/src/main/webapp/WEB-INF/views/professor/lecPlan.jsp

[동호] 강의계획서 조회수정삭제

---

choongangGroup/src/main/java/com/oracle/choongangGroup/hs/lecManagement/LecManagementController.java
choongangGroup/src/main/java/com/oracle/choongangGroup/hs/managerPage/ManagerPageController.java
choongangGroup/src/main/webapp/WEB-INF/views/manager/lecManagementForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/makeupManagement.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/mypage.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/professorManage.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/studentManage.jsp

[혜선] 통합 커밋

---

choongangGroup/src/main/webapp/WEB-INF/views/manager/lecManagementForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/makeupManagement.jsp

[혜선 ] 최종수정

---

choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalEndDetail.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalForm.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalProcessDetail.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalWaitDetail.jsp
choongangGroup/src/main/webapp/WEB-INF/views/manager/mypage.jsp

[혜선] 통합 후 오류 수정

---

choongangGroup/src/main/webapp/WEB-INF/views/manager/mypage.jsp

[혜선] 마이페이지 비번변경 연결

---

choongangGroup/src/main/webapp/WEB-INF/views/manager/approvalForm.jsp

[혜선] 결재폼 수정
